### PR TITLE
Event editing bugs fixed and datetime not set to localtime anymore

### LINKED ISSUE #129: [PE-D] Attendance add is case sensative for event name
When having multiple events, user may forget the precise spelling for each event. 

1. To reproduce bug, just type an uppercase or different case for an event name when prompted by the attendance command

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: rsanchez-macias/ped#12

### LINKED ISSUE #135: [PE-D] editdatetime command updates time when wrong input is given
Bug: when entering a wrong input for editdatetime command, the app catches the problem. However, it updates the past date and time to the current date and time from my computer. So the previous data and time are lost. 

1. To reproduce, edit date and time for an item in the list with a wrong input. Last data/time information is lost.

User may not want the app to change the data/time for them when they are trying to change it.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: rsanchez-macias/ped#6

### LINKED ISSUE #139: [PE-D] Unexpected date/time message when entering an event
To reproduce bug:
1. Enter the input shown in the screenshot (an event without date and time)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: rsanchez-macias/ped#2

### LINKED ISSUE #143: [PE-D] Attendance taking when name duplicates
Users are unable to tell which event exactly is the attendance taken under if event name duplicates

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: Jeremy733/ped#5

### LINKED ISSUE #144: [PE-D] Date and time reset to NOW when editing
When a invalid date and time is passed in , the event date and time is changed to the date and time now. Probably it is better to leave it unchanged when new date is invalid. Also the problem can be found everytime date input is missing. Even when user just want to change the name of a existing event.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: Jeremy733/ped#4

### LINKED ISSUE #148: [PE-D] Can add events with same name.
It seems that PAC can add different events which have the same name.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: RenzoTsai/ped#4

### LINKED ISSUE #150: [PE-D] Process edit venue
The same issue as edit event name. If omit [venue], it still works.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: RenzoTsai/ped#2

### LINKED ISSUE #151: [PE-D] Event edit name's process
It seems that if I omit [editname] in this command, it will still change the name into "nameless"

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: RenzoTsai/ped#1

### PR DESCRIPTION
**Pull request by harithadiv**

### CODE REVIEW

File: src/main/java/seedu/event/DateTime.java [hunk 1]
```diff
@@ -33,15 +37,15 @@ public LocalDateTime getDateTime() {
         try {
             return LocalDateTime.parse(dateTime, DateTimeFormatter.ofPattern("yyyy-MM-dd HHmm"));
         } catch (DateTimeParseException e) {
-            if (!isAutoSet) {
-                UI.display("Unknown DateTime format provided. DateTime is set to local time in the format: "
-                        + "yyyy-MM-dd HHmm.");
-            }
-            isAutoSet = true;
-            return LocalDateTime.now();
+            isInvalid = true;
```
Comment (lowjiayee) [inline src/main/java/seedu/event/DateTime.java:40]: Why not this version?
```
if (!isAutoSet) {
    UI.display("Unknown DateTime format provided. DateTime is set to local time in the format: "
                + "yyyy-MM-dd HHmm.");
    isAutoSet = true;
}
```

Comment (harithadiv) [reply src/main/java/seedu/event/DateTime.java:40]: Need another variable to check whether the parsing is done right, and if the error message for the wrong parsing is required - check EventList#add and EventList#editDateTime. In this case, null Localdatetime is returned when datetimeparseexception encountered in DateTime class

**Review by lowjiayee — APPROVED** [review]
Looks good
