### PR TITLE
Anqi - Update help, DG diagram and DG

### LINKED ISSUE #69: Adding to Developer Guide
Adding into Developer Guide by Week 10

### LINKED ISSUE #146: [PE-D] Help page only takes input once without terminating message
When help page is triggered, it only takes the next input as the index. 
It may mislead users to think the help page is broken since it does not respond any further.
Better to add a message.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: Jeremy733/ped#1

### LINKED ISSUE #169: Draft the PPP
Link your PR relating to PPP to this issue 

https://nus-cs2113-ay1920s2.github.io/website/schedule/week12/project.html#2-draft-the-ppp

### PR DESCRIPTION
**Pull request by Anqi-nus**

### CODE REVIEW

File: src/main/java/seedu/performance/PerformanceList.java [hunk 1]
```diff
@@ -139,7 +139,7 @@ public Performance getPerformance(String studentName) throws PacException {
             throw new PacException("No performance list under this event");
         }
         for (Performance performance: performanceList) {
-            if (performance.studentName.equals(studentName)) {
+            if (isSame(performance.studentName,studentName)) {
```
Comment (harithadiv) [inline src/main/java/seedu/performance/PerformanceList.java]: perhaps isSame to isSameString?

File: src/main/java/seedu/ui/Help.java [hunk 2]
```diff
@@ -40,15 +42,17 @@ public void printEventHelp() {
...
     }
 
     public void printCalendarHelp() {
         display("To view events in a calendar, there should be events that exist in the event list.");
-        display("\tTo view calendar, input: s/Semester_Number ay/Year_one-Year_two.\n");
+        display("To view calendar, input: s/Semester_Number ay/Year_one-Year_two.\n");
         display("* Note that semester can only be an integer 1 or 2.");
         display("* Note that the academic year must contain two consecutive years separated by a hyphen.\n "
                 + " Each year should be in a double digit format.");
+        display("Enter 'list' for command format list. To exit help function, enter 'back'\n");
```
Comment (harithadiv) [inline src/main/java/seedu/ui/Help.java:55]: Why list under Calendar?

File: docs/UserGuide.md [hunk 3]
```diff
@@ -799,6 +874,8 @@ allow users to add more types of events in this application.
 * Add performance `performance add`
 * View performance list `performance list`
```
Comment (lowjiayee) [inline docs/UserGuide.md]: I think this command is changed to performance `list` right? Perhaps can update here also.

File: docs/DeveloperGuide.md [hunk 4]
```diff
@@ -238,22 +240,72 @@ than using the mouse.
...
 1. Edit an existing event's venue by typing   
-`event editvenue i/INDEX v/VENUE`
+`event editvenue i/INDEX v/VENUE`  
+
+**Calender**
 1. Display calendar by entering  
-`calendar s/SEMESTER ay/YEAR_ONE-YEAR_TWO`
+`calendar s/SEMESTER ay/YEAR_ONE-YEAR_TWO`   
 
+#### Follow **step-by-step** command for following commands:
```
Comment (benchan911) [inline docs/DeveloperGuide.md:269]: Perhaps for this step-by-step command,  we can also insert in images on the possible ways of using the respective command?

File: docs/UserGuide.md [hunk 5]
```diff
@@ -664,7 +666,7 @@ Example:
     Attendance List is sorted by attendance status for Event: event1
     
 ### 4.5. Performance
```
Comment (benchan911) [inline docs/UserGuide.md]: Regarding the `Performance` category, I'm not too sure if it would be better to change it to `Performance List` since everything under this heading is about `Performance List` instead of `Performance`

File: docs/UserGuide.md [hunk 6]
```diff
@@ -723,11 +727,63 @@ Step by step guide:
...
+#### 4.5.4. Edit Performance List
+Edit the list of students' result under a certain event.  
+This is a step by step command and you may follow the instructions given by the console. 
+During the process, you can choose to edit either student's name or result.
+
+Format: `performance edit`
+    
+Step by step guide to edit name: 
+
+    >>> performance edit
```
Comment (benchan911) [inline docs/UserGuide.md:741]: `Performance edit` guide might need to add in the extra spacing to fit our current tp

File: docs/UserGuide.md [hunk 7]
```diff
@@ -744,13 +800,20 @@ Step by step guide:
            
        Event is not found in the list.
        
-1. If there are no students' data in the student list:
+1. If there is no students' data in the student list:
```
Comment (benchan911) [inline docs/UserGuide.md]: Perhaps you can change the phrasing to "If the student list collection is empty:  "

File: src/main/java/seedu/command/Help.java [hunk 8]
```diff
@@ -13,30 +14,31 @@ public Help() {
...
-            help.printCalendarHelp();
-            break;
-        case "4":
-            help.printAttendanceHelp();
-            break;
-        case "5":
-            help.printPerformanceHelp();
-            break;
-        default: throw new PacException("Invalid help function selected.");
+        while (!typeOfHelp.equals("back")) {
```
Comment (benchan911) [inline src/main/java/seedu/command/Help.java:21]: For this new change, will the user be allowed to input "back" to exit back to the main part of PAC?

File: src/main/java/seedu/ui/Help.java [hunk 9]
```diff
@@ -4,15 +4,17 @@
...
             + "2. Event-related\n"
             + "3. Calendar\n"
-            + "4. Attendance\n" + "5. Peformance\n"
+            + "4. Attendance\n"
+            + "5. Performance\n"
         );
-        output.append("To track any list, input: <type_of_list> list\n");
-        output.append("Note: All command are NOT case sensitive.\n");
-
+        output.append("To view event list, input: event list\n");
```
Comment (benchan911) [inline src/main/java/seedu/ui/Help.java:14]: For the output.append, why are we appending multiple lines instead of 1 long string with "\n"?

**Review by benchan911 — CHANGES_REQUESTED** [review]
I think your refactoring of Performance to PerformanceList is fine. There are some parts I would like some clarification to better understand your work.

File: src/main/java/seedu/ui/Help.java (hunk 2 above)
Comment (Anqi-nus) [reply src/main/java/seedu/ui/Help.java:55]: this is for command format, now help function requires user to input 'back' to exit

Comment (Anqi-nus) [reply src/main/java/seedu/ui/Help.java:55]: this is for command format, now help function requires user to input 'back' to exit

File: docs/UserGuide.md (hunk 3 above)
Comment (Anqi-nus) [reply docs/UserGuide.md]: right!

File: docs/UserGuide.md (hunk 5 above)
Comment (Anqi-nus) [reply docs/UserGuide.md]: valid point! will change that

File: src/main/java/seedu/command/Help.java (hunk 8 above)
Comment (Anqi-nus) [reply src/main/java/seedu/command/Help.java:21]: yep, they input 'back' to go back to the 'home page'

File: src/main/java/seedu/ui/Help.java (hunk 9 above)
Comment (Anqi-nus) [reply src/main/java/seedu/ui/Help.java:14]: im following jia yee's way, might need to ask him for this

File: docs/UserGuide.md (hunk 7 above)
Comment (Anqi-nus) [reply docs/UserGuide.md]: ok

File: docs/DeveloperGuide.md (hunk 4 above)
Comment (Anqi-nus) [reply docs/DeveloperGuide.md:269]: it sounds like ug to me, could u elaborate more?

File: src/main/java/seedu/performance/PerformanceList.java (hunk 1 above)
Comment (Anqi-nus) [reply src/main/java/seedu/performance/PerformanceList.java]: valid point
