### PR TITLE
Edit Attendance

### LINKED ISSUE #106: Fix Attendance: only shows "unknown command" after requesting for event name
Screenshot from 2020-03-27 20-42-31

### LINKED ISSUE #107: Fix Attendance: only shows "event not found in list" despite wrong attendance command
image

### PR DESCRIPTION
**Pull request by benchan911**
Refactoring

### CODE REVIEW

File: src/main/java/seedu/command/attendance/AddAttendanceList.java [hunk 1]
```diff
@@ -0,0 +1,102 @@
...
+
+import static seedu.duke.Duke.studentListCollection;
+
+public class AddAttendanceList extends Command {
+
+    static UI ui = new UI();
+    AttendanceList attendances;
+    boolean isByNameList;
+    String eventName;
+    DisplayList displayList;
```
Comment (lowjiayee) [inline src/main/java/seedu/command/attendance/AddAttendanceList.java]: package-private? For Unit Test?

Comment (lowjiayee) [reply src/main/java/seedu/command/attendance/AddAttendanceList.java]: Also why need declare ui as static?

Comment (benchan911) [reply src/main/java/seedu/command/attendance/AddAttendanceList.java]: my mistake, ui should be static. I will also declare all the types

**Review by lowjiayee — COMMENTED** [review]
Looks ok to me

File: src/main/java/seedu/StudentListCollection.java [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+
+    public StudentListCollection() {
+        studentListCollection = new ArrayList<>();
+    }
+
+    @Override
+    public String toString() {
+        String data = "";
+        for (StudentList studentList: this.studentListCollection) {
+            data = data.concat("\n" + studentList.toString());
```
Comment (lowjiayee) [inline src/main/java/seedu/StudentListCollection.java]: Can try to have `studentList.toString() + "\n"`?

I used `System.lineSeparator()` instead of `\n`, maybe can help change that?

**Review by lowjiayee — CHANGES_REQUESTED** [review]
I will probably incorporate StudentListStorageParser to my Storage class, when you are done

File: src/main/java/seedu/StudentListCollection.java [hunk 3]
```diff
@@ -0,0 +1,21 @@
...
+
+    public StudentListCollection() {
+        studentListCollection = new ArrayList<>();
+    }
+
+    @Override
+    public String toString() {
+        String data = "";
+        for (StudentList studentList: this.studentListCollection) {
+            data = data.concat(System.lineSeparator() + studentList.toString());
```
Comment (lowjiayee) [inline src/main/java/seedu/StudentListCollection.java]: pls help to swap `System.lineSeparator()` and `studentList.toString()`

**Review by lowjiayee — COMMENTED** [review]
Everything else looks ok

File: src/main/java/seedu/attendance/AttendanceList.java [hunk 4]
```diff
@@ -1,34 +1,34 @@
...
 
     public AttendanceList() {
         this.ui = new UI();
         this.displayTable = new DisplayTable();
         attendanceList = new ArrayList<>();
     }
 
-    public ArrayList<Attendance> getAttendanceList() {
-        return attendanceList;
-    }
```
Comment (lowjiayee) [inline src/main/java/seedu/attendance/AttendanceList.java:26]: I'm adding this back, for the purpose of Storage

Comment (lowjiayee) [reply src/main/java/seedu/attendance/AttendanceList.java:26]: @benchan911
