### PR TITLE
Event-related fix

### LINKED ISSUE #136: [PE-D] Feedback given for non-integer input for delete command
To reproduce, enter a non-integer value as an input for delete command.

User doesn't know what the EventParser is. Feedback may be confusing.

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: rsanchez-macias/ped#5

### PR DESCRIPTION
**Pull request by lowjiayee**
- Update exception messages shown to user to be more user-friendly.

### CODE REVIEW

File: src/main/java/seedu/parser/EventParser.java [hunk 1]
```diff
@@ -143,6 +121,13 @@ private void splitByEventFlags(String[] tokens) throws DukeException {
                     mostRecent = "venue";
                     break;
                 case "i/":
+                    ensureNotDuplicateFlag(venue, "EventParser: Duplicate index flag");
+                    try {
+                        index = Integer.parseInt(token.substring(2));
```
Comment (harithadiv) [inline src/main/java/seedu/parser/EventParser.java:87]: Perhaps can write a parseIndex method for cleaner code?

File: src/main/java/seedu/parser/EventParser.java [hunk 2]
```diff
@@ -56,48 +55,48 @@ private void splitByEventFlags(String[] tokens) throws PacException {
...
+                    ensureNotDuplicateFlag(venue, "venue");
                     venue += token.substring(2);
                     mostRecent = "venue";
                     break;
                 case "i/":
-                    ensureNotDuplicateFlag(index, "EventParser: Duplicate index flag");
+                    ensureNotDuplicateFlag(index, "index");
                     try {
                         index = Integer.parseInt(token.substring(2));
                     } catch (NumberFormatException m) {
```
Comment (harithadiv) [inline src/main/java/seedu/parser/EventParser.java:67]: Perhaps can write this try catch block in a different method for cleaner code?

Comment (harithadiv) [reply src/main/java/seedu/parser/EventParser.java:67]: Just a suggestion (:

File: src/main/java/seedu/command/interpreter/SeminarCommandInterpreter.java [hunk 3]
```diff
@@ -62,7 +62,7 @@ public Command decideCommand(String commandDescription) throws PacException {
             break;
```
Comment (harithadiv) [inline src/main/java/seedu/command/interpreter/SeminarCommandInterpreter.java:63]: Perhaps eventParser.parse(commandParameters) can be written before the case statements to avoid repetition?

File: src/main/java/seedu/parser/EventParser.java [hunk 4]
```diff
@@ -128,19 +127,20 @@ private void append(String mostRecent, String token) throws PacException {
             venue += venue.isEmpty() ? token : (" " + token);
             break;
         default:
-            throw new PacException("EventParser: Invalid flag to append to");
+            throw new PacException("I am not sure '" + token + "' belongs to which flag. "
+                    + "Is a flag provided beforehand?");
```
Comment (harithadiv) [inline src/main/java/seedu/parser/EventParser.java:110]: Question in exception makes it confusing...maybe can add a statement that it is an invalid flag.

Comment (lowjiayee) [reply src/main/java/seedu/parser/EventParser.java:110]: I wanted to suggest to user what to do, instead of only telling them what's wrong.

Anyway, my testing so far shows that this message won't be seen by a user. Either the part without flag is ignored, or the user will see `flag is too short`.
image

File: src/main/java/seedu/parser/EventParser.java (hunk 2 above)
Comment (lowjiayee) [reply src/main/java/seedu/parser/EventParser.java:67]: The `try... catch` block is quite short though... If I refactor this, then I feel also should refactor other cases also. But other cases only take 2 lines.
